package spells;

import java.util.Map;

import attributes.Attributes;
import main.Elements;
import main.Path;

public abstract class SpellData
{
    public static void createSpells()
    {
        new Spell(0, "", "", "", SpellTypes.offensive, 80, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight0.png", 5, 20, Map.of(), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.02, 1.0))) ;
        new Spell(1, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight1.png", 5, -1, Map.of(0, 3), -1, -1, Map.of()) ;
        new Spell(2, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight2.png", 5, -1, Map.of(0, 3), -1, -1, Map.of()) ;
        new Spell(3, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight3.png", 5, -1, Map.of(0, 3), -1, -1, Map.of()) ;
        new Spell(4, "", "", "", SpellTypes.support, 100, 20, Elements.neutral, Path.SPELLS_IMG + "spellknight4.png", 5, 40, Map.of(1, 3), -1, -1, Map.of()) ;
        new Spell(5, "", "", "", SpellTypes.support, 80, 150, Elements.neutral, Path.SPELLS_IMG + "spellknight5.png", 5, 30, Map.of(2, 3), 1, -1, Map.of()) ;
        new Spell(6, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight6.png", 5, 40, Map.of(3, 3), -1, -1, Map.of(Attributes.magDef, new AttMod(-0.04, 0.0), Attributes.dex, new AttMod(0.01, 0.0), Attributes.critAtk, new AttMod(0.01, 0.0))) ;
        new Spell(7, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight7.png", 5, -1, Map.of(4, 3), -1, -1, Map.of()) ;
        new Spell(8, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight8.png", 5, 50, Map.of(5, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.04, 10.0), Attributes.critAtk, new AttMod(0.01, 0.0))) ;
        new Spell(9, "", "", "", SpellTypes.support, 200, 150, Elements.neutral, Path.SPELLS_IMG + "spellknight9.png", 5, 5, Map.of(6, 3), 2, -1, Map.of()) ;
        new Spell(10, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight10.png", 5, -1, Map.of(7, 3), -1, -1, Map.of()) ;
        new Spell(11, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellknight11.png", 5, -1, Map.of(8, 3), -1, -1, Map.of()) ;
        new Spell(12, "", "", "", SpellTypes.support, 100, 150, Elements.neutral, Path.SPELLS_IMG + "spellknight12.png", 5, 40, Map.of(9, 3), 3, -1, Map.of()) ;
        new Spell(13, "", "", "", SpellTypes.offensive, 50, 20, Elements.neutral, Path.SPELLS_IMG + "spellknight13.png", 5, 50, Map.of(10, 3, 11, 3, 12, 3), 4, -1, Map.of(Attributes.magAtk, new AttMod(0.05, 10.0), Attributes.critAtk, new AttMod(0.04, 0.0))) ;
        new Spell(14, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord14.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(15, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord15.png", 5, 80, Map.of(14, 3), -1, -1, Map.of()) ;
        new Spell(16, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord16.png", 5, 80, Map.of(14, 3), -1, -1, Map.of()) ;
        new Spell(17, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord17.png", 5, 80, Map.of(15, 3), 5, -1, Map.of()) ;
        new Spell(18, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord18.png", 5, -1, Map.of(16, 3), -1, -1, Map.of()) ;
        new Spell(19, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord19.png", 5, -1, Map.of(17, 3), -1, -1, Map.of()) ;
        new Spell(20, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord20.png", 5, 90, Map.of(18, 3), 6, -1, Map.of()) ;
        new Spell(21, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord21.png", 5, 150, Map.of(19, 3), -1, -1, Map.of()) ;
        new Spell(22, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord22.png", 5, 150, Map.of(20, 3), 7, -1, Map.of()) ;
        new Spell(23, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spelllord23.png", 5, -1, Map.of(21, 3, 22, 3), -1, -1, Map.of()) ;
        new Spell(24, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder24.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(25, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder25.png", 5, 80, Map.of(24, 3), -1, -1, Map.of()) ;
        new Spell(26, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder26.png", 5, 80, Map.of(24, 3), -1, -1, Map.of()) ;
        new Spell(27, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder27.png", 5, -1, Map.of(25, 3), -1, -1, Map.of()) ;
        new Spell(28, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder28.png", 5, -1, Map.of(26, 3), -1, -1, Map.of()) ;
        new Spell(29, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder29.png", 5, -1, Map.of(27, 3), -1, -1, Map.of()) ;
        new Spell(30, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder30.png", 5, 120, Map.of(28, 3), -1, -1, Map.of()) ;
        new Spell(31, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder31.png", 5, 120, Map.of(29, 3), -1, -1, Map.of()) ;
        new Spell(32, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder32.png", 5, 150, Map.of(30, 3), -1, -1, Map.of()) ;
        new Spell(33, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellshielder33.png", 5, 150, Map.of(31, 3, 32, 3), -1, -1, Map.of()) ;
        new Spell(34, "", "", "", SpellTypes.offensive, 60, -1, Elements.fire, Path.SPELLS_IMG + "spellmage34.png", 5, 20, Map.of(), -1, -1, Map.of(Attributes.magAtk, new AttMod(0, 2.0))) ;
        new Spell(35, "", "", "", SpellTypes.offensive, 20, -1, Elements.water, Path.SPELLS_IMG + "spellmage35.png", 5, 20, Map.of(), -1, -1, Map.of(Attributes.magAtk, new AttMod(0, 2.0))) ;
        new Spell(36, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellmage36.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(37, "", "", "", SpellTypes.offensive, 20, -1, Elements.air, Path.SPELLS_IMG + "spellmage37.png", 5, 30, Map.of(34, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0, 2.0))) ;
        new Spell(38, "", "", "", SpellTypes.offensive, 20, -1, Elements.earth, Path.SPELLS_IMG + "spellmage38.png", 5, 30, Map.of(35, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0, 2.0))) ;
        new Spell(39, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmage39.png", 5, 30, Map.of(36, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0, 5.0))) ;
        new Spell(40, "", "", "", SpellTypes.offensive, 50, -1, Elements.air, Path.SPELLS_IMG + "spellmage40.png", 5, 50, Map.of(37, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.02, 5.0))) ;
        new Spell(41, "", "", "", SpellTypes.offensive, 50, -1, Elements.water, Path.SPELLS_IMG + "spellmage41.png", 5, 50, Map.of(38, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.02, 5.0))) ;
        new Spell(42, "", "", "", SpellTypes.auto, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellmage42.png", 5, -1, Map.of(39, 3), -1, -1, Map.of()) ;
        new Spell(43, "", "", "", SpellTypes.offensive, 150, 150, Elements.neutral, Path.SPELLS_IMG + "spellmage43.png", 5, 50, Map.of(40, 3), -1, -1, Map.of()) ;
        new Spell(44, "", "", "", SpellTypes.support, 100, -1, Elements.neutral, Path.SPELLS_IMG + "spellmage44.png", 5, 70, Map.of(41, 3), -1, -1, Map.of()) ;
        new Spell(45, "", "", "", SpellTypes.support, 200, 50, Elements.neutral, Path.SPELLS_IMG + "spellmage45.png", 5, 70, Map.of(42, 3), 8, -1, Map.of()) ;
        new Spell(46, "", "", "", SpellTypes.offensive, 50, -1, Elements.fire, Path.SPELLS_IMG + "spellmage46.png", 5, 70, Map.of(43, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.02, 5.0))) ;
        new Spell(47, "", "", "", SpellTypes.offensive, 50, -1, Elements.earth, Path.SPELLS_IMG + "spellmage47.png", 5, 80, Map.of(44, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.02, 5.0))) ;
        new Spell(48, "", "", "", SpellTypes.offensive, 100, -1, Elements.neutral, Path.SPELLS_IMG + "spellmage48.png", 5, 80, Map.of(45, 3), -1, -1, Map.of()) ;
        new Spell(49, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage49.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(50, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage50.png", 5, 120, Map.of(49, 3), -1, -1, Map.of()) ;
        new Spell(51, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage51.png", 5, 120, Map.of(49, 3), -1, -1, Map.of()) ;
        new Spell(52, "", "", "", SpellTypes.offensive, 50, -1, Elements.thunder, Path.SPELLS_IMG + "spellarquimage52.png", 5, 120, Map.of(50, 3), -1, -1, Map.of()) ;
        new Spell(53, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage53.png", 5, 400, Map.of(51, 3), -1, -1, Map.of()) ;
        new Spell(54, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage54.png", 5, -1, Map.of(52, 3), -1, -1, Map.of()) ;
        new Spell(55, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage55.png", 5, 400, Map.of(53, 3), -1, -1, Map.of()) ;
        new Spell(56, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage56.png", 5, 750, Map.of(54, 3), -1, -1, Map.of()) ;
        new Spell(57, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage57.png", 5, 750, Map.of(55, 3), -1, -1, Map.of()) ;
        new Spell(58, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarquimage58.png", 5, 2000, Map.of(56, 3, 57, 3), -1, -1, Map.of()) ;
        new Spell(59, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer59.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(60, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer60.png", 5, 20, Map.of(59, 3), -1, -1, Map.of()) ;
        new Spell(61, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer61.png", 5, 120, Map.of(59, 3), -1, -1, Map.of()) ;
        new Spell(62, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer62.png", 5, -1, Map.of(60, 3), -1, -1, Map.of()) ;
        new Spell(63, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer63.png", 5, 120, Map.of(61, 3), -1, -1, Map.of()) ;
        new Spell(64, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer64.png", 5, -1, Map.of(62, 3), -1, -1, Map.of()) ;
        new Spell(65, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer65.png", 5, 400, Map.of(63, 3), -1, -1, Map.of()) ;
        new Spell(66, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer66.png", 5, 400, Map.of(64, 3), -1, -1, Map.of()) ;
        new Spell(67, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer67.png", 5, 800, Map.of(65, 3), -1, -1, Map.of()) ;
        new Spell(68, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellhealer68.png", 5, 1200, Map.of(66, 3, 67, 3), -1, -1, Map.of()) ;
        new Spell(69, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher69.png", 5, 15, Map.of(), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.0, 2.0))) ;
        new Spell(70, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher70.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(71, "", "", "", SpellTypes.offensive, 30, -1, Elements.fire, Path.SPELLS_IMG + "spellarcher71.png", 5, 20, Map.of(), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.0, 2.0))) ;
        new Spell(72, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher72.png", 5, 50, Map.of(69, 3), -1, -1, Map.of(Attributes.dex, new AttMod(-0.1, 0.0))) ;
        new Spell(73, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher73.png", 5, -1, Map.of(70, 3), -1, -1, Map.of()) ;
        new Spell(74, "", "", "", SpellTypes.offensive, 30, -1, Elements.snow, Path.SPELLS_IMG + "spellarcher74.png", 5, 20, Map.of(72, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.0, 2.0))) ;
        new Spell(75, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher75.png", 5, 30, Map.of(73, 3), -1, -1, Map.of(Attributes.critAtk, new AttMod(0.1, 0.0))) ;
        new Spell(76, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher76.png", 5, -1, Map.of(74, 3), -1, -1, Map.of()) ;
        new Spell(77, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher77.png", 5, -1, Map.of(75, 3), -1, -1, Map.of()) ;
        new Spell(78, "", "", "", SpellTypes.offensive, 80, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher78.png", 5, 50, Map.of(76, 3), -1, -1, Map.of()) ;
        new Spell(79, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher79.png", 5, -1, Map.of(77, 3), -1, -1, Map.of()) ;
        new Spell(80, "", "", "", SpellTypes.offensive, 30, -1, Elements.thunder, Path.SPELLS_IMG + "spellarcher80.png", 5, 20, Map.of(78, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.0, 2.0))) ;
        new Spell(81, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher81.png", 5, 150, Map.of(79, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.1, 0.0))) ;
        new Spell(82, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher82.png", 5, -1, Map.of(80, 3), -1, -1, Map.of()) ;
        new Spell(83, "", "", "", SpellTypes.offensive, 150, -1, Elements.neutral, Path.SPELLS_IMG + "spellarcher83.png", 5, 80, Map.of(81, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.2, 5.0))) ;
        new Spell(84, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger84.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(85, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger85.png", 1, 150, Map.of(84, 3), -1, -1, Map.of()) ;
        new Spell(86, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger86.png", 5, -1, Map.of(84, 3), -1, -1, Map.of()) ;
        new Spell(87, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger87.png", 5, 150, Map.of(85, 1), -1, -1, Map.of()) ;
        new Spell(88, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger88.png", 5, 150, Map.of(86, 3), -1, -1, Map.of()) ;
        new Spell(89, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger89.png", 5, 250, Map.of(87, 3), -1, -1, Map.of()) ;
        new Spell(90, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger90.png", 5, 250, Map.of(88, 3), -1, -1, Map.of()) ;
        new Spell(91, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger91.png", 5, 300, Map.of(89, 3), -1, -1, Map.of()) ;
        new Spell(92, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger92.png", 5, 300, Map.of(90, 3), -1, -1, Map.of()) ;
        new Spell(93, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellranger93.png", 5, 300, Map.of(91, 3, 92, 3), -1, -1, Map.of()) ;
        new Spell(94, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist94.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(95, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist95.png", 5, 180, Map.of(94, 3), -1, -1, Map.of()) ;
        new Spell(96, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist96.png", 5, 180, Map.of(94, 3), -1, -1, Map.of()) ;
        new Spell(97, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist97.png", 5, 250, Map.of(95, 3), -1, -1, Map.of()) ;
        new Spell(98, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist98.png", 5, 250, Map.of(96, 3), -1, -1, Map.of()) ;
        new Spell(99, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist99.png", 5, -1, Map.of(97, 3), -1, -1, Map.of()) ;
        new Spell(100, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist100.png", 5, 300, Map.of(98, 3), -1, -1, Map.of()) ;
        new Spell(101, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist101.png", 5, 300, Map.of(99, 3), -1, -1, Map.of()) ;
        new Spell(102, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist102.png", 5, 330, Map.of(100, 3), -1, -1, Map.of()) ;
        new Spell(103, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellelementalist103.png", 5, 330, Map.of(101, 3, 102, 3), -1, -1, Map.of()) ;
        new Spell(104, "", "", "", SpellTypes.offensive, 60, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal104.png", 5, 20, Map.of(), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.02, 1.0))) ;
        new Spell(105, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal105.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(106, "", "", "", SpellTypes.offensive, 30, 80, Elements.neutral, Path.SPELLS_IMG + "spellanimal106.png", 5, 30, Map.of(104, 3), -1, -1, Map.of()) ;
        new Spell(107, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal107.png", 5, -1, Map.of(104, 3, 105, 3), -1, -1, Map.of()) ;
        new Spell(108, "", "", "", SpellTypes.auto, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal108.png", 5, -1, Map.of(105, 3), -1, -1, Map.of()) ;
        new Spell(109, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal109.png", 5, 40, Map.of(107, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.05, 0.0))) ;
        new Spell(110, "", "", "", SpellTypes.support, 150, 300, Elements.neutral, Path.SPELLS_IMG + "spellanimal110.png", 5, 50, Map.of(108, 3), 9, -1, Map.of()) ;
        new Spell(111, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal111.png", 5, -1, Map.of(109, 3), -1, -1, Map.of()) ;
        new Spell(112, "", "", "", SpellTypes.support, 50, 150, Elements.neutral, Path.SPELLS_IMG + "spellanimal112.png", 5, 60, Map.of(110, 3), -1, -1, Map.of()) ;
        new Spell(113, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal113.png", 5, -1, Map.of(111, 3), -1, -1, Map.of()) ;
        new Spell(114, "", "", "", SpellTypes.passive, -1, 10, Elements.neutral, Path.SPELLS_IMG + "spellanimal114.png", 5, -1, Map.of(112, 3), -1, -1, Map.of()) ;
        new Spell(115, "", "", "", SpellTypes.offensive, 100, 100, Elements.neutral, Path.SPELLS_IMG + "spellanimal115.png", 5, 90, Map.of(113, 3), 13, -1, Map.of(Attributes.magAtk, new AttMod(0.03, 0.0), Attributes.critAtk, new AttMod(0.03, 0.0), Attributes.dex, new AttMod(0.0, 2.0))) ;
        new Spell(116, "", "", "", SpellTypes.auto, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal116.png", 5, -1, Map.of(114, 3), 14, -1, Map.of()) ;
        new Spell(117, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellanimal117.png", 5, -1, Map.of(115, 3), -1, -1, Map.of()) ;
        new Spell(118, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing118.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(119, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing119.png", 5, 170, Map.of(118, 3), -1, -1, Map.of()) ;
        new Spell(120, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing120.png", 5, 180, Map.of(118, 3), -1, -1, Map.of()) ;
        new Spell(121, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing121.png", 5, 180, Map.of(119, 3), -1, -1, Map.of()) ;
        new Spell(122, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing122.png", 5, 200, Map.of(120, 3), -1, -1, Map.of()) ;
        new Spell(123, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing123.png", 5, 210, Map.of(121, 3), -1, -1, Map.of()) ;
        new Spell(124, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing124.png", 5, 220, Map.of(122, 3), -1, -1, Map.of()) ;
        new Spell(125, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing125.png", 5, 220, Map.of(123, 3), -1, -1, Map.of()) ;
        new Spell(126, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing126.png", 5, 240, Map.of(124, 3), -1, -1, Map.of()) ;
        new Spell(127, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellforestKing127.png", 5, 240, Map.of(125, 3, 126, 3), -1, -1, Map.of()) ;
        new Spell(128, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild128.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(129, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild129.png", 5, 20, Map.of(128, 3), -1, -1, Map.of()) ;
        new Spell(130, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild130.png", 5, 120, Map.of(128, 3), -1, -1, Map.of()) ;
        new Spell(131, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild131.png", 5, 150, Map.of(129, 3), -1, -1, Map.of()) ;
        new Spell(132, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild132.png", 5, -1, Map.of(130, 3), -1, -1, Map.of()) ;
        new Spell(133, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild133.png", 5, 180, Map.of(131, 3), -1, -1, Map.of()) ;
        new Spell(134, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild134.png", 5, 180, Map.of(132, 3), -1, -1, Map.of()) ;
        new Spell(135, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild135.png", 5, 200, Map.of(133, 3), -1, -1, Map.of()) ;
        new Spell(136, "", "", "", SpellTypes.passive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild136.png", 5, 200, Map.of(134, 3), -1, -1, Map.of()) ;
        new Spell(137, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellwild137.png", 5, 220, Map.of(135, 3, 136, 3), -1, -1, Map.of()) ;
        new Spell(138, "", "", "", SpellTypes.offensive, 45, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief138.png", 5, 20, Map.of(), -1, -1, Map.of()) ;
        new Spell(139, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief139.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(140, "", "", "", SpellTypes.offensive, 20, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief140.png", 5, 30, Map.of(138, 3), -1, -1, Map.of(Attributes.critAtk, new AttMod(0.05, 0.0), Attributes.dex, new AttMod(0.0, 1.0))) ;
        new Spell(141, "", "", "", SpellTypes.support, 150, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief141.png", 5, 30, Map.of(138, 3, 139, 3), -1, -1, Map.of()) ;
        new Spell(142, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief142.png", 5, -1, Map.of(139, 3), -1, -1, Map.of()) ;
        new Spell(143, "", "", "", SpellTypes.offensive, 30, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief143.png", 5, 50, Map.of(140, 3), -1, -1, Map.of(Attributes.magAtk, new AttMod(0.03, 0.0), Attributes.dex, new AttMod(0.0, 2.0))) ;
        new Spell(144, "", "", "", SpellTypes.passive, 500, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief144.png", 5, -1, Map.of(147, 3), -1, -1, Map.of()) ;
        new Spell(145, "", "", "", SpellTypes.offensive, 150, 150, Elements.neutral, Path.SPELLS_IMG + "spellthief145.png", 5, 1, Map.of(142, 3), 16, 1, Map.of()) ;
        new Spell(146, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief146.png", 5, -1, Map.of(143, 3), -1, -1, Map.of()) ;
        new Spell(147, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief147.png", 5, -1, Map.of(144, 3), -1, 2, Map.of()) ;
        new Spell(148, "", "", "", SpellTypes.support, 150, 150, Elements.neutral, Path.SPELLS_IMG + "spellthief148.png", 5, 70, Map.of(145, 3), 17, -1, Map.of()) ;
        new Spell(149, "", "", "", SpellTypes.auto, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief149.png", 5, -1, Map.of(146, 3), -1, -1, Map.of()) ;
        new Spell(150, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief150.png", 5, 50, Map.of(141, 3), 15, -1, Map.of()) ;
        new Spell(151, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellthief151.png", 5, -1, Map.of(148, 3), -1, -1, Map.of()) ;
        new Spell(152, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary152.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(153, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary153.png", 5, -1, Map.of(152, 3), -1, -1, Map.of()) ;
        new Spell(154, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary154.png", 5, -1, Map.of(152, 3), -1, -1, Map.of()) ;
        new Spell(155, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary155.png", 5, 180, Map.of(153, 3), -1, -1, Map.of()) ;
        new Spell(156, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary156.png", 5, 180, Map.of(154, 3), -1, -1, Map.of()) ;
        new Spell(157, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary157.png", 5, 250, Map.of(155, 3), -1, -1, Map.of()) ;
        new Spell(158, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary158.png", 5, 250, Map.of(156, 3), -1, -1, Map.of()) ;
        new Spell(159, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary159.png", 5, -1, Map.of(157, 3), -1, -1, Map.of()) ;
        new Spell(160, "", "", "", SpellTypes.offensive, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary160.png", 5, 220, Map.of(158, 3), -1, -1, Map.of()) ;
        new Spell(161, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellmercenary161.png", 5, 120, Map.of(159, 3, 160, 3), -1, -1, Map.of()) ;
        new Spell(162, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin162.png", 5, -1, Map.of(), -1, -1, Map.of()) ;
        new Spell(163, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin163.png", 5, 120, Map.of(162, 3), -1, -1, Map.of()) ;
        new Spell(164, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin164.png", 5, 130, Map.of(162, 3), -1, -1, Map.of()) ;
        new Spell(165, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin165.png", 5, 150, Map.of(163, 3), -1, -1, Map.of()) ;
        new Spell(166, "", "", "", SpellTypes.passive, -1, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin166.png", 5, -1, Map.of(164, 3), -1, -1, Map.of()) ;
        new Spell(167, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin167.png", 5, 170, Map.of(165, 3), -1, -1, Map.of()) ;
        new Spell(168, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin168.png", 5, 170, Map.of(166, 3), -1, -1, Map.of()) ;
        new Spell(169, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin169.png", 5, 190, Map.of(167, 3), -1, -1, Map.of()) ;
        new Spell(170, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin170.png", 5, 190, Map.of(168, 3), -1, -1, Map.of()) ;
        new Spell(171, "", "", "", SpellTypes.support, 50, -1, Elements.neutral, Path.SPELLS_IMG + "spellassassin171.png", 5, 200, Map.of(169, 3, 170, 3), -1, -1, Map.of()) ;
    }
}
