package main;

public enum TextCategories
{	
	allIsGood("tudo está bem"),
	attributes("atributos"),
	bagMenus("menus da mochila"),
	bestiary("bestiário"),
	classes("classes"),
	equipments("equipamentos"),
	hints("menu de dicas"),
	newGame("novo jogo"),
	

	npcs("NPCs"),
	alchemistSpeech("npcsAlquimistaFalas"),
	alchemistOptions0("npcsAlquimistaOpcoes0"),
	alchemistOptions1("npcsAlquimistaOpcoes1"),
	alchemistOptions2("npcsAlquimistaOpcoes2"),
	alchemistOptions3("npcsAlquimistaOpcoes3"),
	alchemistOptions4("npcsAlquimistaOpcoes4"),
	bankerSpeech("npcsBanqueiroFalas"),
	bankerOptions0("npcsBanqueiroOpcoes0"),
	bankerOptions1("npcsBanqueiroOpcoes1"),
	bankerOptions2("npcsBanqueiroOpcoes2"),
	bankerOptions3("npcsBanqueiroOpcoes3"),
	bankerOptions4("npcsBanqueiroOpcoes4"),
	bankerOptions5("npcsBanqueiroOpcoes5"),
	bankerOptions6("npcsBanqueiroOpcoes6"),
	bankerOptions7("npcsBanqueiroOpcoes7"),
	bankerOptions8("npcsBanqueiroOpcoes8"),
	bankerOptions9("npcsBanqueiroOpcoes9"),
	citzen0Speech("npcsCidadão 0Falas"),
	citzen0Options0("npcsCidadão 0Opcoes0"),
	citzen0Options1("npcsCidadão 0Opcoes1"),
	citzen0Options2("npcsCidadão 0Opcoes2"),
	citzen1Speech("npcsCidadão 1Falas"),
	citzen1Options0("npcsCidadão 1Opcoes0"),
	citzen1Options1("npcsCidadão 1Opcoes1"),
	citzen1Options2("npcsCidadão 1Opcoes2"),
	citzen2Speech("npcsCidadão 2Falas"),
	citzen2Options0("npcsCidadão 2Opcoes0"),
	citzen2Options1("npcsCidadão 2Opcoes1"),
	citzen2Options2("npcsCidadão 2Opcoes2"),
	citzen3Speech("npcsCidadão 3Falas"),
	citzen3Options0("npcsCidadão 3Opcoes0"),
	citzen3Options1("npcsCidadão 3Opcoes1"),
	citzen3Options2("npcsCidadão 3Opcoes2"),
	citzen4Speech("npcsCidadão 4Falas"),
	citzen4Options0("npcsCidadão 4Opcoes0"),
	citzen4Options1("npcsCidadão 4Opcoes1"),
	citzen4Options2("npcsCidadão 4Opcoes2"),
	citzen5Speech("npcsCidadão 5Falas"),
	citzen5Options0("npcsCidadão 5Opcoes0"),
	citzen5Options1("npcsCidadão 5Opcoes1"),
	citzen5Options2("npcsCidadão 5Opcoes2"),
	citzen6Speech("npcsCidadão 6Falas"),
	citzen6Options0("npcsCidadão 6Opcoes0"),
	citzen6Options1("npcsCidadão 6Opcoes1"),
	citzen6Options2("npcsCidadão 6Opcoes2"),
	citzen7Speech("npcsCidadão 7Falas"),
	citzen7Options0("npcsCidadão 7Opcoes0"),
	citzen7Options1("npcsCidadão 7Opcoes1"),
	citzen7Options2("npcsCidadão 7Opcoes2"),
	citzen8Speech("npcsCidadão 8Falas"),
	citzen8Options0("npcsCidadão 8Opcoes0"),
	citzen8Options1("npcsCidadão 8Opcoes1"),
	citzen8Options2("npcsCidadão 8Opcoes2"),
	citzen9Speech("npcsCidadão 9Falas"),
	citzen9Options0("npcsCidadão 9Opcoes0"),
	citzen9Options1("npcsCidadão 9Opcoes1"),
	citzen9Options2("npcsCidadão 9Opcoes2"),
	citzen10Speech("npcsCidadão 10Falas"),
	citzen10Options0("npcsCidadão 10Opcoes0"),
	citzen10Options1("npcsCidadão 10Opcoes1"),
	citzen10Options2("npcsCidadão 10Opcoes2"),
	citzen11Speech("npcsCidadão 11Falas"),
	citzen11Options0("npcsCidadão 11Opcoes0"),
	citzen11Options1("npcsCidadão 11Opcoes1"),
	citzen11Options2("npcsCidadão 11Opcoes2"),
	citzen12Speech("npcsCidadão 12Falas"),
	citzen12Options0("npcsCidadão 12Opcoes0"),
	citzen12Options1("npcsCidadão 12Opcoes1"),
	citzen12options2("npcsCidadão 12Opcoes2"),
	citzen13Speech("npcsCidadão 13Falas"),
	citzen13Options0("npcsCidadão 13Opcoes0"),
	citzen13Options1("npcsCidadão 13Opcoes1"),
	citzen13Options2("npcsCidadão 13Opcoes2"),
	citzen14Speech("npcsCidadão 14Falas"),
	citzen14Options0("npcsCidadão 14Opcoes0"),
	citzen14Options1("npcsCidadão 14Opcoes1"),
	citzen14Options2("npcsCidadão 14Opcoes2"),
	citzen15Speech("npcsCidadão 15Falas"),
	citzen15Options0("npcsCidadão 15Opcoes0"),
	citzen15Options1("npcsCidadão 15Opcoes1"),
	citzen15Options2("npcsCidadão 15Opcoes2"),
	citzen16Speech("npcsCidadão 16Falas"),
	citzen16Options0("npcsCidadão 16Opcoes0"),
	citzen16Options1("npcsCidadão 16Opcoes1"),
	citzen16Options2("npcsCidadão 16Opcoes2"),
	citzen17Speech("npcsCidadão 17Falas"),
	citzen17Options0("npcsCidadão 17Opcoes0"),
	citzen17Options1("npcsCidadão 17Opcoes1"),
	citzen17Options2("npcsCidadão 17Opcoes2"),
	citzen18Speech("npcsCidadão 18Falas"),
	citzen18Options0("npcsCidadão 18Opcoes0"),
	citzen18Options1("npcsCidadão 18Opcoes1"),
	citzen18Options2("npcsCidadão 18Opcoes2"),
	citzen19Speech("npcsCidadão 19Falas"),
	citzen19Options0("npcsCidadão 19Opcoes0"),
	citzen19Options1("npcsCidadão 19Opcoes1"),
	citzen19Options2("npcsCidadão 19Opcoes2"),
	crafterSpeech("npcsFabricanteFalas"),
	crafterOptions0("npcsFabricanteOpcoes0"),
	crafterOptions1("npcsFabricanteOpcoes1"),
	crafterOptions2("npcsFabricanteOpcoes2"),
	crafterOptions3("npcsFabricanteOpcoes3"),
	crafterOptions4("npcsFabricanteOpcoes4"),
	crafterOptions5("npcsFabricanteOpcoes5"),
	doctorSpeech("npcsDoutorFalas"),
	doctorOptions0("npcsDoutorOpcoes0"),
	doctorOptions1("npcsDoutorOpcoes1"),
	elementalSpeech("npcsElementalFalas"),
	elementalOptions0("npcsElementalOpcoes0"),
	elementalOptions1("npcsElementalOpcoes1"),
	elementalOptions2("npcsElementalOpcoes2"),
	elementalOptions3("npcsElementalOpcoes3"),
	elementalOptions4("npcsElementalOpcoes4"),
	elementalOptions5("npcsElementalOpcoes5"),
	elementalOptions6("npcsElementalOpcoes6"),
	equipsSellerSpeech("npcsVendedor de equipamentosFalas"),
	equipsSellerOptions0("npcsVendedor de equipamentosOpcoes0"),
	equipsSellerOptions1("npcsVendedor de equipamentosOpcoes1"),
	equipsSellerOptions2("npcsVendedor de equipamentosOpcoes2"),
	forgerSpeech("npcsForjadorFalas"),
	forgerOptions0("npcsForjadorOpcoes0"),
	forgerOptions1("npcsForjadorOpcoes1"),
	forgerOptions2("npcsForjadorOpcoes2"),
	forgerOptions3("npcsForjadorOpcoes3"),
	forgerOptions4("npcsForjadorOpcoes4"),
	forgerOptions5("npcsForjadorOpcoes5"),
	forgerOptions6("npcsForjadorOpcoes6"),
	forgerOptions7("npcsForjadorOpcoes7"),
	itemsSellerSpeech("npcsVendedor de itensFalas"),
	itemsSellerOptions0("npcsVendedor de itensOpcoes0"),
	itemsSellerOptions1("npcsVendedor de itensOpcoes1"),
	itemsSellerOptions2("npcsVendedor de itensOpcoes2"),
	masterSpeech("npcsMestreFalas"),
	masterOptions0("npcsMestreOpcoes0"),
	masterOptions1("npcsMestreOpcoes1"),
	masterOptions2("npcsMestreOpcoes2"),
	masterOptions3("npcsMestreOpcoes3"),
	masterOptions4("npcsMestreOpcoes4"),
	masterOptions5("npcsMestreOpcoes5"),
	masterOptions6("npcsMestreOpcoes6"),
	questExpSpeech("npcsQuest expFalas"),
	questExpOptions0("npcsQuest expOpcoes0"),
	questExpOptions1("npcsQuest expOpcoes1"),
	questExpOptions2("npcsQuest expOpcoes2"),
	questExpOptions3("npcsQuest expOpcoes3"),
	questExpOptions4("npcsQuest expOpcoes4"),
	questItemSpeech("npcsQuest itemFalas"),
	questItemOptions0("npcsQuest itemOpcoes0"),
	questItemOptions1("npcsQuest itemOpcoes1"),
	questItemOptions2("npcsQuest itemOpcoes2"),
	questItemOptions3("npcsQuest itemOpcoes3"),
	questItemOptions4("npcsQuest itemOpcoes4"),
	sailorToIslandSpeech("npcsNavegador 1Falas"),
	sailorToIslandOptions0("npcsNavegador 1Opcoes0"),
	sailorToForestSpeech("npcsNavegador 2Falas"),
	sailorToForestOptions0("npcsNavegador 2Opcoes0"),
	saverSpeech("npcsSalvadorFalas"),
	saverOptions0("npcsSalvadorOpcoes0"),
	saverOptions1("npcsSalvadorOpcoes1"),
	saverOptions2("npcsSalvadorOpcoes2"),
	saverOptions3("npcsSalvadorOpcoes3"),
	smugglerSpeech("npcsContrabandistaFalas"),
	smugglerOptions0("npcsContrabandistaOpcoes0"),
	smugglerOptions1("npcsContrabandistaOpcoes1"),
	smugglerOptions2("npcsContrabandistaOpcoes2"),
	woodcrafterSpeech("npcsMadeireiroFalas"),
	woodcrafterOptions0("npcsMadeireiroOpcoes0"),
	woodcrafterOptions1("npcsMadeireiroOpcoes1"),
	woodcrafterOptions2("npcsMadeireiroOpcoes2"),
	woodcrafterOptions3("npcsMadeireiroOpcoes3"),
	woodcrafterOptions4("npcsMadeireiroOpcoes4"),
	
	
	settings("menu de opções"),
	signMessages("mensagem das placas"),
	specialAttributesProperties("propriedades dos atributos especiais"),
	spellsBar("barra de magias"),
	statistics("estatísticas do jogador"),
	playerWindow("janela do jogador"),
	proclasses("proClasses"),
	pterodactile("pterodactile");
	
	public static TextCategories catFromBRName(String brName)
	{
		
		for (TextCategories cat : TextCategories.values())
		{
			if (cat.brName.equals(brName))
			{
				return cat ;
			}
		}

		return null ;
		
	}
	
	private String brName ;
	
	public String getBrName()
	{
		return brName;
	}

	private TextCategories(String brName)
	{
		this.brName = brName ;
	}
}
